version: "3"

services:
  web:
    platform: linux/amd64 # Compatible con Mac M1 (arm64 aarch)
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    volumes:
      - ".:/usr/src/app"
    ports:
      - "3000:3000"
    depends_on:
      - db 
      - postgress
    stdin_open: true # Using for debug
    tty: true

  postgress:
    platform: linux/amd64 # Compatible con Mac M1 (arm64 aarch)
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: development
      POSTGRES_USER: the_user
      POSTGRES_PASSWORD: the_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db:
    platform: linux/amd64 # Compatible con Mac M1 (arm64 aarch) 
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: development
      MYSQL_USER: the_user
      MYSQL_PASSWORD: the_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /:/var/lib/mysql_database

  redis:
    platform: linux/amd64
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data

  worker:
    platform: linux/amd64
    depends_on:
      - 'db'
      - 'redis'
      - 'web'
    build: .
    volumes:
      - ".:/app"
    command: bundle exec sidekiq # don't mount tmp directory
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1

volumes:
  redis:
  postgres_data:
  mysql_data: